### ISSUE TITLE
I have an analysis with another tool (e.g. Signac), can I still use dictys？

### ISSUE THREAD

**Issue by LalicJ** [pinellolab/dictys#19]
Hi, I now have the data (10x multiome) for the basic analysis done with Signac, and I want to use it to analyze the specific gene regulatory network. Is there any way to analyze it with dictys directly in Signac format? Or can I get the required input file by format conversion?
I will be appreciated it if you can reply me soon, Thank you all!

**Comment by lingfeiwang** [comment]
Hi LalicJ,

Thank you for your interest.

Dictys should work straight away with 10x multiome datasets, although it does not have Signac interface at the moment. We provide several tutorials at https://github.com/pinellolab/dictys#tutorials. I suggest to start with the tutorial `short-multiome` at https://github.com/pinellolab/dictys/tree/master/doc/tutorials/short-multiome.

If you prefer to use cell type annotations from Signac, you can export them and replace the subsets folder and subsets.txt file with the matched formats. You can see the expected formats easily by running the tutorial.

Just let us know if you encounter any issue in the process.

Lingfei

**Comment by LalicJ** [comment]
Thank you for reply! I will try it.
