### ISSUE TITLE
dynamic regulatory strength plot(with pseudotime)

### ISSUE THREAD

**Issue by willey2020** [pinellolab/dictys#21]
Thank you again for this wonderful package.

Could I ask a small question regarding figure 5d(Figure s6 middle panel) , could I ask how to generate this dynamic regulatory strength plot with pseudotime on the x axis? Could you provide the example code during the dynamic GRN analysis?

Thank you so much!

**Comment by lingfeiwang** [comment]
Hi willey2020,

Thank you for the question. We are working on adding this plotting function to the software. This can take some time.

But if you prefer not to wait, you can achieve it very easily. You can first export the continuous dynamic network with sufficient time points (https://nbviewer.org/github/pinellolab/dictys/blob/master/doc/tutorials/analysis-blood/notebooks/dynamic/main.ipynb#Export-dynamic-network-to-folder). Then you can extract the regulation(s) of interest and show a heatmap over pseudotime. This was exactly what we did.

Hope that answers your question.

Lingfei

**Comment by willey2020** [comment]
Dear Lingfei,

Thank you so much for your answer! Yes I can do that! Thank you again!

Best,
willey
