### ISSUE TITLE
Other motifs from other motif database?

### ISSUE THREAD

**Issue by willey2020** [pinellolab/dictys#22]
Dear Lingfei,

Thank you again for this great package. I am also wondering if there is a way to input other motifs from other databases or other species into the pipeline? Thank you again!

Best,
Willey

**Comment by lingfeiwang** [comment]
Hi Willey,

Yes. You can use any custom species, genome, or motif files.

You just need to replace the "Other files" section (e.g. https://github.com/pinellolab/dictys/blob/master/doc/tutorials/short-multiome/notebooks/main.ipynb) with your own files in the `data` folder. You need to convert them to the same format as those in the tutorial datasets.

Let us know if you encounter any particular problem in the process.

Lingfei

**Comment by willey2020** [comment]
Thank you so much Lingfei! I will give it a try!

Best,
Willey
