### ISSUE TITLE
where I can find update-makefile-variables.py?

### ISSUE THREAD

**Issue by bitcometz** [pinellolab/dictys#34]
**Checks before submitting the issue**
* [x] I installed the latest Dictys version successfully
* [ ] I downloaded the whole folder for the tutorial
* [ ] I ran the tutorial cells and notebooks (if more than one) in the correct order and only once
* [ ] The preceeding cells and notebooks finished successfully (i.e. the reported error is the first encountered)

**Describe the error**
* Which tutorial?
```python
#Download makefile update script
wget -q https://raw.githubusercontent.com/pinellolab/dictys/master/.github/scripts/update-makefile-variables.py
```

I cannot download the py file?
Could you help with this problem?

Thanks !!!

**Comment by lingfeiwang** [comment]
Actually the Google Colab tutorial is very outdated. Thank you for alerting us to remove it! You can use other tutorials on Google Colab too as long as you set up the conda environment properly. Please let us know if you have any problem on that.
