### ISSUE TITLE
How to use separate scRNA-seq and scATAC-seq data to Create dynamic GRN ?

### ISSUE THREAD

**Issue by thinkingpeach-z** [pinellolab/dictys#36]
Dear Lingfei,

Thank you for developing such a wonderful package. I noticed that in the tutorial, it mentioned that the Human blood data was used to construct a dynamic GNR based on separate scRNA-seq and scATAC-seq. I also have separate data. How can I use Dictys to construct a dynamic GNR?

**Comment by lingfeiwang** [comment]
Dear thinkingpeach-z,

Thank you for your interest. You need to integrate them into the same low dimensions. Then you can infer a trajectory in this low dimension with both data types together, in the same way as the dynamic GRN for SHARE-seq or 10x multiome in other tutorials. You also need to set JOINT to 0 in the configuration step. Other steps are the same with the tutorial. Please let us know here if you have any followup questions.
