### ISSUE TITLE
Can I run dictys with 10X multiome?

### ISSUE THREAD

**Issue by massonix** [pinellolab/dictys#4]
Hi Dictys team,

Congrats on this package, it looks really promising! I saw it in your poster at the Single Cell Biology in Hinxton.

I have a 10X multiome dataset for which I would like to model gene regulatory networks using both modalities, so your package would, in principle be amazing for this. Do you have any step-by-step tutorial on this? Ideally it would be a jupyter notebook starting from the "outs" folder produced by cellranger-arc.

Also, will dictys integrate with data containers for single-cell multiomics data, such as Seurat or muon?

Thanks in advance! I can help you beta-test your tool :)

Ramon

**Comment by lingfeiwang** [comment]
Hi Ramon,

Thank you for your interest!

We are indeed working on a tutorial with an official 10x multiome example dataset. We will update you here when it's available and would love to hear your feedbacks!

Single-cell network is an emerging field. Unfortunately existing data containers don't quite support the needed data structure, such as networks and raw reads of chromatin accessibility. For some preprocessing steps such as cell clustering, trajectory inference, and multi-modal integration, we allow users to freely choose their favorite software beyond any provided one. If there's growing demand for preprocessing tutorials, we can surely add some gradually, like the current STREAM tutorial provided.

Lingfei

**Comment by massonix** [comment]
Thanks for the info Lingfei!

Yes, I would love to beta-test your tool, so as soon as you have a working pipeline for multiome, perhaps we could have a meeting over zoom to discuss how to run it with my data. Your tool seems incredible, and I think it can become the gold-standard for GRN inference with multimodal data. To make this happen, I think you just need to improve the usability of the tool (which you are doing already), and I could help you with that if you want!

Ramon

**Comment by lingfeiwang** [comment]
Indeed, Ramon. We would love to work together to improve Dictys for best user experience! Let us first have the manuscript ready so you have the whole story, and meanwhile the multiome tutorial ready too so we can start working together! We will reach out to you by email very soon.

Lingfei

**Comment by massonix** [comment]
That sounds like a really good plan. Best of luck with the paper, I'm sure it will be amazing!

Ramon

**Comment by lingfeiwang** [comment]
Hi Ramon.

We have added a 10x multiome tutorial from data download to network inference and analysis at https://github.com/pinellolab/dictys/tree/master/doc/tutorials/full-multiome/ . This only includes cell-type specific GRNs and works on the latest version. We are working on converting other tutorials into similar formats to include as many scenarios as possible.

Let us know what you think. We are happy to hear your feedbacks or perform troubleshooting! We are also available if you have additional questions to discuss. In that case, just drop a line and we can email you.

Lingfei

**Comment by massonix** [comment]
Hi @lingfeiwang, sorry for the delay, I am currently not focused on analyzing my multiome data . I think @PauBadiaM might be interested in running your tutorial :)

**Comment by lingfeiwang** [comment]
Hi Ramon. No problem. Thanks for letting us know!
