### ISSUE TITLE
Four multiome samples, 2 different treatment conditions 

### ISSUE THREAD

**Issue by kfenggg** [pinellolab/dictys#45]
Hello,

Thank you so much for developing this tool! I am interested in running GRN inference on 4 multiome samples (2 treated, 2 untreated). What is the best way to run your pipeline on all 4 samples together? Ie. Should I integrate with seurat, extract gex mtx and create an ATAC bed and convert to bams?

Thanks!

Kev

**Comment by lingfeiwang** [comment]
Hi Kev,

You can follow "How do I use Dictys on multiple samples?" in FAQ. Let us know if you have further questions.

Lingfei
