### ISSUE TITLE
Can I integrate my own scRNA-seq data and bulk ATAC-seq data?

### ISSUE THREAD

**Issue by 13021969200** [pinellolab/dictys#46]
Dear author: 

  I have a few samples of single-cell RNA and bulk ATAC sequencing data, can I integrate my own data through Dictys?

  Besides, the samples were from acute myeloid leukemia patients, and there were tumor cells in the samples, can I annote tumor cells through Dictys?

  Thank you very much!

**Comment by lingfeiwang** [comment]
Thanks for the questions.

Dictys can infer GRNs for cells that are already annotated. You can follow https://github.com/pinellolab/dictys/issues/23#issuecomment-1641035864 for bulk ATAC-seq data.

**Comment by 13021969200** [comment]
Thanks very much for your timely reply!
I still want to consult that I have already annotated the cell type in my scRNA-seq data, but I can't use the cell type information migrating to my bulk ATAC-seq data. I have read the #23 (comment) for bulk ATAC-seq data, does it mean that I can use my bulk ATAC-seq peak which contains tumor cells to get the cell type through you already annotated cell type from scATAC-seq data?And through the analysis using Dictys, can I get the integrated results containing both the scRNA-seq and bulk ATAC-seq data?
Thank you very much!
--------------------------------

 小舟从此逝 江海寄余生


----- 原始邮件 -----
发件人：Lingfei Wang ***@***.***>
收件人：pinellolab/dictys ***@***.***>
抄送人：13021969200 ***@***.***>,  Author ***@***.***>
主题：Re: [pinellolab/dictys] Can I integrate my own scRNA-seq data and bulk ATAC-seq data? (Issue #46)
日期：2023年12月16日 11点53分


Thanks for the questions.
Dictys can infer GRNs for cells that are already annotated. You can follow #23 (comment) for bulk ATAC-seq data.

**Comment by 13021969200** [comment]
Thanks very much for your timely reply!I still want to consult that I have already annotated the cell type in my scRNA-seq data, but I can't use the cell type information migrating to my bulk ATAC-seq data. I have read the #23 (comment) for bulk ATAC-seq data, does it mean that I can use my bulk ATAC-seq peak which contains tumor cells to get the cell type through you already annotated cell type from scATAC-seq data?And through the analysis using Dictys, can I get the integrated results containing both the scRNA-seq and bulk ATAC-seq data?Thank you very much!
--------------------------------

 小舟从此逝 江海寄余生


----- 原始邮件 -----
发件人：Lingfei Wang ***@***.***>
收件人：pinellolab/dictys ***@***.***>
抄送人：13021969200 ***@***.***>,  Author ***@***.***>
主题：Re: [pinellolab/dictys] Can I integrate my own scRNA-seq data and bulk ATAC-seq data? (Issue #46)
日期：2023年12月16日 11点53分


Thanks for the questions.
Dictys can infer GRNs for cells that are already annotated. You can follow #23 (comment) for bulk ATAC-seq data.

**Comment by lingfeiwang** [comment]
Hello. Dictys does not annotate cell types. It reconstructs GRNs. You can look for other methods for integration or cell type annotation.

**Comment by 13021969200** [comment]
Thanks for you timely reply, I will look for other methods for integration or cell type annotation.
Thank you!
--------------------------------

 小舟从此逝 江海寄余生


----- 原始邮件 -----
发件人：Lingfei Wang ***@***.***>
收件人：pinellolab/dictys ***@***.***>
抄送人：13021969200 ***@***.***>,  Author ***@***.***>
主题：Re: [pinellolab/dictys] Can I integrate my own scRNA-seq data and bulk ATAC-seq data? (Issue #46)
日期：2023年12月18日 12点18分


Hello. Dictys does not annotate cell types. It reconstructs GRNs. You can look for other methods for integration or cell type annotation.
