### ISSUE TITLE
Error when running STREAM trajectory inference on co-embedded data (following in the full-skin tutorial)

### ISSUE THREAD

**Issue by HarrisHan2k** [pinellolab/dictys#47]
HI Lingfei,

I encountered this error when running the STREAM trajectory inference following the main1 textbook in the full-skin tutorial.

I prepared the data and reconstructed the adata with cell type and co-embedded UMAP coordinates. However, when I run the stream trajectory inference code in the full-skin main1 tutorial, I encountered this error:

RRuntimeError Traceback (most recent call last)
/tmp/ipykernel_817251/378101491.py in
11 with TemporaryDirectory() as td:
12 st.set_workdir(adata,td)
---> 13 st.elastic_principal_graph(adata,**ka1)
14 st.extend_elastic_principal_graph(adata,**ka2)
15

/media/dell/Elements/soft/conda/miniconda3/envs/env_stream/lib/python3.7/site-packages/stream/core.py in elastic_principal_graph(adata, epg_n_nodes, incr_n_nodes, epg_lambda, epg_mu, epg_trimmingradius, epg_finalenergy, epg_alpha, epg_beta, epg_n_processes, use_vis, save_fig, fig_name, fig_path, fig_size, **kwargs)
2026 nReps=1,
2027 ProbPoint=1.0,
-> 2028 **kwargs)
2029 R('dev.off()')
2030

/media/dell/Elements/soft/conda/miniconda3/envs/env_stream/lib/python3.7/site-packages/rpy2/robjects/functions.py in call(self, *args, **kwargs)
176 v = kwargs.pop(k)
177 kwargs[r_k] = v
--> 178 return super(SignatureTranslatedFunction, self).call(*args, **kwargs)
179
180 pattern_link = re.compile(r'\link{(.+?)}')

/media/dell/Elements/soft/conda/miniconda3/envs/env_stream/lib/python3.7/site-packages/rpy2/robjects/functions.py in call(self, *args, **kwargs)
104 for k, v in kwargs.items():
105 new_kwargs[k] = conversion.py2ri(v)
--> 106 res = super(Function, self).call(*new_args, **new_kwargs)
107 res = conversion.ri2ro(res)
108 return res

RRuntimeError: Error: object ‘palette.colors’ is not exported by 'namespace:grDevices'

It seemed like the R used for stream did not have palette.colors function in their build-in grDevices package, could I see the environment you use for STREAM trajectory inference?

**Comment by lingfeiwang** [comment]
Duplicate issue https://github.com/pinellolab/STREAM/issues/144
