### ISSUE TITLE
ChIP-seq datasets from Cistrome database and ChIP-seq + HiC results for evaluation

### ISSUE THREAD

**Issue by Zengggg** [pinellolab/dictys#48]
Dear authors,

I read the paper and found that you have collected ChIP-seq datasets from Cistrome database and ChIP-seq + HiC results to assess the performance of GRN inference methods. I wonder if you can share the results, which will be very helpful for me.

Thank you very much!

**Comment by lingfeiwang** [comment]
Hi Zengggg. Thank you for your interest. You can follow the links or accession codes in our Data availability section to download these data. If you have any followup questions. Please do not hesitate to let us know.
