### ISSUE TITLE
Creating .h5 output file

### ISSUE THREAD

**Issue by e-arslan** [pinellolab/dictys#49]
Hi thanks for the method. 

I'm having an issue while running Aggregating network part

make -f makefiles/static.mk combine

mkdir -p output/
OPENBLAS_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_MAX_THREADS=1 NUMEXPR_MAX_THREADS=1 MKL_MAX_THREADS=1 python3 -m dictys  network tofile  data tmp_static data/subsets.txt output/static.h5
WARNING:27658:2024-01-07 18:59:19,742:/Users/earslan/opt/anaconda3/envs/dictys/lib/python3.9/site-packages/dictys/net/__init__.py:403:Skipping cell subset pt_28_c1d1 due to error: FileNotFoundError(2, 'No such file or directory')
WARNING:27658:2024-01-07 18:59:19,743:/Users/earslan/opt/anaconda3/envs/dictys/lib/python3.9/site-packages/dictys/net/__init__.py:403:Skipping cell subset pt_28_c1d1 due to error: FileNotFoundError(2, 'No such file or directory')
WARNING:27658:2024-01-07 18:59:19,743:/Users/earslan/opt/anaconda3/envs/dictys/lib/python3.9/site-packages/dictys/net/__init__.py:403:Skipping cell subset pt_28_c1d3 due to error: FileNotFoundError(2, 'No such file or directory')
WARNING:27658:2024-01-07 18:59:19,744:/Users/earslan/opt/anaconda3/envs/dictys/lib/python3.9/site-packages/dictys/net/__init__.py:403:Skipping cell subset pt_28_c1d3 due to error: FileNotFoundError(2, 'No such file or directory')
WARNING:27658:2024-01-07 18:59:19,744:/Users/earslan/opt/anaconda3/envs/dictys/lib/python3.9/site-packages/dictys/net/__init__.py:403:Skipping cell subset pt_28_c1d8 due to error: FileNotFoundError(2, 'No such file or directory')
WARNING:27658:2024-01-07 18:59:19,744:/Users/earslan/opt/anaconda3/envs/dictys/lib/python3.9/site-packages/dictys/net/__init__.py:403:Skipping cell subset pt_28_c1d8 due to error: FileNotFoundError(2, 'No such file or directory')
WARNING:27658:2024-01-07 18:59:19,745:/Users/earslan/opt/anaconda3/envs/dictys/lib/python3.9/site-packages/dictys/net/__init__.py:403:Skipping cell subset pt_28_c2d1 due to error: FileNotFoundError(2, 'No such file or directory')
WARNING:27658:2024-01-07 18:59:19,745:/Users/earslan/opt/anaconda3/envs/dictys/lib/python3.9/site-packages/dictys/net/__init__.py:403:Skipping cell subset pt_28_c2d1 due to error: FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/Users/earslan/opt/anaconda3/envs/dictys/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/earslan/opt/anaconda3/envs/dictys/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/earslan/opt/anaconda3/envs/dictys/lib/python3.9/site-packages/dictys/__main__.py", line 13, in <module>
    docstringrunner(__package__)
  File "/Users/earslan/opt/anaconda3/envs/dictys/lib/python3.9/site-packages/docstring2argparse/__init__.py", line 340, in docstringrunner
    run_args(pkgname,funcs,args)
  File "/Users/earslan/opt/anaconda3/envs/dictys/lib/python3.9/site-packages/docstring2argparse/__init__.py", line 330, in run_args
    return func(*a,**ka)
  File "/Users/earslan/opt/anaconda3/envs/dictys/lib/python3.9/site-packages/dictys/network.py", line 1074, in tofile
    n=network.from_folders(diri_data,diri_work,fi_subsets,dynamic=dynamic,nettype=nettype,optional=optional,fi_c=fi_c)
  File "/Users/earslan/opt/anaconda3/envs/dictys/lib/python3.9/site-packages/dictys/net/__init__.py", line 407, in from_folders
    raise RuntimeError('No network found.')
RuntimeError: No network found.
make: *** [makefiles/common.mk:178: output/static.h5] Error 1

**Comment by lingfeiwang** [comment]
Hi, thanks for the interest. Did you run the tutorial successfully?

**Comment by lingfeiwang** [comment]
Hi, thanks for the interest. Did you run the tutorial successfully?
