### ISSUE TITLE
network strength

### ISSUE THREAD

**Issue by Trafalgar-ROOM** [pinellolab/dictys#50]
Hi,
Thank you for developing the tool. I have a question regarding the interpretation of network (edge) strength. I'm wondering what does negative sign mean and if the strengths could be directly comparable between different networks.
Thanks.

**Comment by lingfeiwang** [comment]
Hi. Thank you for the interest!

Negative sign indicates inferred repression. In our paper, we performed comparative network analyses between cell types and along continuous developmental trajectories, such as the comparison of regulatory activity (target gene count) of TFs and the strength of individual regulations. Their underlying assumption is that the strengths are directly comparable between different networks derived from different cell subsets in the same dataset. 

Hope that answers your question.

**Comment by Trafalgar-ROOM** [comment]
I see, thank you very much.
