### ISSUE TITLE
dictys_helper

### ISSUE THREAD

**Issue by nikithkurella** [pinellolab/dictys#51]
Hello,

I've installed Dictys via Anaconda as written in the instructions. However, upon running the tutorial notebooks, I get an error indicating that the dictys_helper command is not found. How would I go about getting this set up? Thank you.

**Comment by lingfeiwang** [comment]
Hi nikithkurella,

Thanks for the question. We have not encountered this error before. Did you install it with a different user? Do you have multiple Dictys installed on your system? Have you set PATH?

Alternatively, can you provide a shell script that installs Dictys and reproduces your error from a clean docker OS image so we can troubleshoot?

If you want to use CPU for Dictys, you can also use our container image.

On Jan 28, 2024, at 17:00, nikithkurella ***@***.***> wrote:

﻿

Hello,

I've installed Dictys via Anaconda as written in the instructions. However, upon running the tutorial notebooks, I get an error indicating that the dictys_helper command is not found. How would I go about getting this set up? Thank you.

**Comment by nikithkurella** [comment]
Hi @lingfeiwang 

I tried using the provided container image and the dictys_helper command is recognized. However, I am trying to run dictys on my HPC and take advantage of GPU computation. I've installed dictys on my HPC using:

```

wget https://tinyurl.com/dictys -O - | CUDAVERSION_CONDA=11.7 bash

```
I have not set PATH, which may be why dictys_helper is not recognized. Would you be able to describe how to do so?

**Comment by lingfeiwang** [comment]
Hi nikithkurella. I just tested this method on a clean ubuntu docker image and it worked well. You do not need any extra setting including PATH. Can you provide a minimal shell script to reproduce your issue on a clean docker OS image, such as https://hub.docker.com/_/ubuntu?
