### ISSUE TITLE
errors running full human multiome

### ISSUE THREAD

**Issue by hshcao** [pinellolab/dictys#58]
i need to reproduce these two analyses
[full-multiome](https://www.github.com/pinellolab/dictys/blob/master/doc/tutorials/full-multiome): an extended version of the above tutorial with detailed usage.
[full-skin](https://www.github.com/pinellolab/dictys/blob/master/doc/tutorials/full-skin): a short tutorial for the inference and analysis of dynamic networks on SHARE-seq data for mouse skin. Contains a simple demonstration to account for covariates.

I run into errors runing full-multiome: 1.1 CPU part 1, execution
Here GPU is used to speed up computation. Therefore this part only infers the TF binding network that serves as a constraint for GRN inference.

%%bash
set -eo pipefail
cd ..
#Run CPU part of inference
make -f makefiles/static.mk -j 12 -k cpu || true

got errors like this one: 
<img width="1229" alt="Screenshot 2024-04-25 at 10 18 11 AM" src="https://github.com/pinellolab/dictys/assets/17132685/4186506f-7ed2-4485-be42-e324cd65f43e">

please help: how this problem occur and how to fix it?
in the code above, I believe this is for the human blood samples, the mm should be hs, right?

in this full-multiome analysis, should all four steps, 1.1, 2.1, 3.1, and 4.1 be executed, right?
thanks,
HC

**Checks before submitting the issue**
* [x] I installed the latest Dictys version successfully
* [ ] I downloaded the whole folder for the tutorial
* [ ] I ran the tutorial cells and notebooks (if more than one) in the correct order and only once
* [ ] The preceeding cells and notebooks finished successfully (i.e. the reported error is the first encountered)

**Describe the error**
* How did you install Dictys (which option)?
* Which tutorial?
* What and where was the error?
* Did you deviate from any of the tutorial instructions?

**Optional steps (may accelerate troubleshooting)**
* Attach the error notebook and all preceeding notebooks with run output

**Comment by lingfeiwang** [comment]
Hi hshcao. Could you describe the problem by answering the questions in the issue template before I can help you further?

**Comment by hshcao** [comment]
Hi lingfei,
let me finish the short multiome part and get back to you if I still have any questions.
hc
