### ISSUE TITLE
Dynamic inference errors using custom subsets

### ISSUE THREAD

**Issue by nikithkurella** [pinellolab/dictys#59]
Hi @lingfeiwang. I'm running into an issue with the dynamic inference on my own dataset that I believe is related to the subsets being created in tmp_dynamic. I have created the prerequisite files as outlined in https://github.com/pinellolab/dictys/blob/master/doc/tutorials/full-skin/notebooks/main2.ipynb. However, I noticed that the subsets being generated in tmp_dynamic differ from the custom ones that I created earlier on. I figure I might be able to bypass this issue by creating my own tmp_dynamic folder with my own subsets.txt, subset_locs.h5, and subset_edges.tsv.gz. Could you please advise on how to do so? If the errors stem from a separate issue, any help would be much appreciated.

I ran:

```
dictys_helper network_inference.sh -j 16 -J 1 dynamic 
```
The output was quite long, so I've attached it as a separate file
[slurm-23089385.txt](https://github.com/pinellolab/dictys/files/15214822/slurm-23089385.txt)
.

**Comment by lingfeiwang** [comment]
Hi nikithkurella,

I can see several types of errors in your output.
* `[bam_sort_core] failed to create temporary file "/project/macleana_13/kurellan/Dictys/yAL/tmp_dynamic/Subset3/reads.bam.tmp.0003.bam": File exists`
You probably ran the steps multiple times and didn't clean the temporary files inbetween. Whenever you fail the `dictys_helper network_inference.sh ...` step, you should delete the `tmp_dynamic` folder or simply recreate the folder structure in a new location.

* `index: invalid option -- '@'`
This indicates you are using the wrong samtools version. Probably you didn't install Dictys properly. Please make sure you ran the tutorials successfully first.

I don't see anything wrong with the subset creation. Note that you didn't create the subsets but only the trajectory as input. Subsets are determined automatically from the trajectory.

Lingfei

**Comment by nikithkurella** [comment]
Thank you for your response @lingfeiwang. I ran the full-skin tutorial with a fresh conda environment prepared with the instructions outlined in the documentation. However, I am still running into the `index: invalid option -- '@'` issue for the tutorial. The environment is currently using samtools 1.3.1 from bioconda. Is this the correct version I should be using?

**Comment by lingfeiwang** [comment]
Hi nikithkurella,

You should check your conda and `PATH` settings. It should install samtools ~1.20. See https://github.com/pinellolab/dictys/actions/runs/8803877738/job/24163840030#step:5:582 .

**Comment by lingfeiwang** [comment]
Hi @nikithkurella,

We have updated Dictys so it can work with older versions of samtools. You can find the details at the bottom of [FAQ](https://github.com/pinellolab/dictys#faq). Please let us know if that doesn't work for you.

Lingfei

**Comment by wangqiuba2024** [comment]
Hi, @lingfeiwang. I'm doing the dynamic inference on my own merged two datasets. The code is 'dictys_helper network_inference.sh -j 8 -J 1 dynamic'.  Is there any problem?

"Traceback (most recent call last):
  File "/share/home/wangxinxin/miniconda3/envs/dictys/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/share/home/wangxinxin/miniconda3/envs/dictys/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/share/home/wangxinxin/miniconda3/envs/dictys/lib/python3.9/site-packages/dictys/__main__.py", line 13, in <module>
    docstringrunner(__package__)
  File "/share/home/wangxinxin/miniconda3/envs/dictys/lib/python3.9/site-packages/docstring2argparse/__init__.py", line 340, in docstringrunner
    run_args(pkgname,funcs,args)
  File "/share/home/wangxinxin/miniconda3/envs/dictys/lib/python3.9/site-packages/docstring2argparse/__init__.py", line 330, in run_args
    return func(*a,**ka)
  File "/share/home/wangxinxin/miniconda3/envs/dictys/lib/python3.9/site-packages/dictys/network.py", line 1074, in tofile
    n=network.from_folders(diri_data,diri_work,fi_subsets,dynamic=dynamic,nettype=nettype,optional=optional,fi_c=fi_c)
  File "/share/home/wangxinxin/miniconda3/envs/dictys/lib/python3.9/site-packages/dictys/net/__init__.py", line 457, in from_folders
    ncprop['readcount']=readcount.values.astype(dtype_min(readcount.values.astype(int)))
  File "/share/home/wangxinxin/miniconda3/envs/dictys/lib/python3.9/site-packages/dictys/utils/numpy.py", line 99, in dtype_min
    t1=np.iinfo(np.dtype(f'{typebase}{itemsize_new}'))
TypeError: data type 'i0' not understood"

**Comment by lingfeiwang** [comment]
Hi wangqiuba2024,

Have you run all the tutorials successfully? If not, please post a standard tutorial issue first.

Lingfei

**Comment by wangqiuba2024** [comment]
Thank you for your reply @lingfeiwang.  there are no problems with the tutorial. Is it a problem with the two data I merged or a problem with the trajectory file? The same data for static analysis did well!

**Comment by lingfeiwang** [comment]
Hi wangqiuba2024,

The error seems to suggest you don't have nonzero values in your input scRNA-seq read count matrix. Can you check if your trajectory contains any cell or any cell subset in scRNA-seq?

**Comment by juanmoriano** [comment]
Hello @lingfeiwang! Thank you for the amazing work on dictys. I am finding the same error as reported above (TypeError: data type 'i0' not understood) while running dictys_helper network_inference.sh -j 32 -J 1 static on my dataset (containing nonzero values). The code works without problem when following the short and full multiome tutorial. I wonder whether you have suggestions on how to address this problem after the previous report (let me also know whether I can provide you with more useful information).

**Comment by lingfeiwang** [comment]
Hi @juanmoriano. Are you doing cell type specific or dynamic GRN inference? How many times does this error appear in the full log? Do you still get the final output file? Can you post the full error?

**Comment by juanmoriano** [comment]
Thank you @lingfeiwang. I am doing the cell type-specific GRN inference, and the error appears just at the end, while writing to output/ ; this folder however remains empty. 

Find the full error file here:
[slurm-354271.out.txt](https://github.com/user-attachments/files/18772963/slurm-354271.out.txt)

**Comment by lingfeiwang** [comment]
As above, the error suggests some problem with your `data/expression.tsv.gz`. Could you check if it looks alright? If so, could you upload a section of it so I can inspect?

**Comment by juanmoriano** [comment]
Find it here - it looks ok to me: [expression.tsv.gz](https://github.com/user-attachments/files/18789143/expression.tsv.gz). For more context, I was working with the output of `cell ranger-arc aggregation` - as I have many samples. This expression matrix was generated from a Seurat object for just one of the samples as a test (first using `write10xCounts` and then `dictys_helper expression_mtx.py`). Since `cell ranger-arc aggregation` does not provide an aggregated bam file, I retrieved the bam file associated to that single sample and changed barcode suffixes in the bam file (from -1 to -51 since after `cell ranger-arc aggregation` a suffix is added to each barcode in the expression matrix, representing sampled index e.g. -51 in this case). The idea being to be able to run dictys on multiple samples assuring unique barcodes.

**Comment by lingfeiwang** [comment]
Thanks, @juanmoriano. The expression file appears good and so let's look elsewhere.
* Have you run the `dictys_helper makefile_check.py` step? If so, could you post the output?
* Can you show what runtime files are available, such as in `ls -l tmp_static/SubsetB45_Astro`?
* If `linking.tsv.gz` is in it, could you share the first few lines and how many lines in total?

**Comment by juanmoriano** [comment]
Thank you! 

- I did run `dictys_helper makefile_check.py`. I post here the output: [makefile_check_output.txt](https://github.com/user-attachments/files/18790576/makefile_check_output.txt).
- Find the runtime files available in tmp_static here: [runtime_files.txt](https://github.com/user-attachments/files/18790596/runtime_files.txt)
- Lines in total of linking.tsv.gz for each cell type are: 128, 149, 171, 114. I can see though -inf values in it: [example_linking.tsv.txt](https://github.com/user-attachments/files/18790718/example_linking.tsv.txt)

**Comment by lingfeiwang** [comment]
Hmm... Oddly they all look good. Is it possible to share the full version of the following files in `tmp_static/SubsetB45_Oligo` for troubleshooting?
* binlinking.tsv.gz
* net_stats.tsv.gz
* net_weight.tsv.gz
* net_loss.tsv.gz
If you prefer to share them elsewhere or parts of them, let me know to discuss how.

**Comment by juanmoriano** [comment]
Sure, find them attached: [tmp_static_files.zip](https://github.com/user-attachments/files/18854044/tmp_static_files.zip). Thank you very much!

**Comment by lingfeiwang** [comment]
These files still look alright. It's hard to understand why unless I can run it on all your data. 

However, there's a quick fix to it. In `config.mk`, Change the line

`KPARAMS-NETWORK-TOFILE:=$(KPARAMS-NETWORK-TOFILE_EXTRA)`

into

`KPARAMS-NETWORK-TOFILE:=$(KPARAMS-NETWORK-TOFILE_EXTRA) --optional ,`

Then you can just rerun the line `!cd ..; dictys_helper network_inference.sh -j 32 -J 1 static` in your jupyter notebook, which should not produce any error. Rerunning the full notebook from the beginning should not be necessary.

The error occured when trying to store the read count matrix into the network h5 file. This extra parameter will omit this optional data in the h5 file, and therefore should bypass this error.

Please let me know if it doesn't work or you have any questions.

Lingfei
