### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'analysis-blood.tar.xz'

### ISSUE THREAD

**Issue by zly19980908** [pinellolab/dictys#64]
**Checks before submitting the issue**
* [x] I installed the latest Dictys version successfully
* [ ] I downloaded the whole folder for the tutorial
* [ ] I ran the tutorial cells and notebooks (if more than one) in the correct order and only once
* [ ] The preceeding cells and notebooks finished successfully (i.e. the reported error is the first encountered)

**Describe the error**
* How did you install Dictys (which option)?
* Which tutorial?
* What and where was the error?
* Did you deviate from any of the tutorial instructions?

**Optional steps (may accelerate troubleshooting)**
* Attach the error notebook and all preceeding notebooks with run output

Dear Author

`import os
os.environ['KMP_AFFINITY'] = ''
# Download network data from zenodo
!cd ../.. && dictys_helper repodown.sh zenodo analysis-blood.tar.xz`

When I run this line of code to download the file, I get the following error, is it because of a directory problem?
Here is the error message：

Downloading analysis-blood.tar.xz
Traceback (most recent call last):
  File "/home/lab501-6/.conda/envs/dictys/lib/python3.9/site-packages/dictys/scripts/helper/repo_zenodo.py", line 154, in <module>
    args.func(args)
  File "/home/lab501-6/.conda/envs/dictys/lib/python3.9/site-packages/dictys/scripts/helper/repo_zenodo.py", line 118, in down
    return d.download(args.src,dst=args.dst)
  File "/home/lab501-6/.conda/envs/dictys/lib/python3.9/site-packages/dictys/scripts/helper/repo_zenodo.py", line 114, in download
    self.download_byurl(fs[src],dst)
  File "/home/lab501-6/.conda/envs/dictys/lib/python3.9/site-packages/dictys/scripts/helper/repo_zenodo.py", line 102, in download_byurl
    with open(dst, 'wb') as f:
PermissionError: [Errno 13] Permission denied: 'analysis-blood.tar.xz'

I'm sure I've recreated a virtual environment and installed dictys as per the tutorial, should I download the entire dictys folder separately and create the file in that folder?
Could you please look at this message, I may be a noob, please advise me.Good Luck!

**Comment by lingfeiwang** [comment]
Hi [zly19980908](https://github.com/zly19980908),

You need to download the whole folder for the tutorial. If the problem persists, please let us know.

Lingfei

**Comment by zly19980908** [comment]
Thanks a lot, I downloaded the whole Dictys package and my problem is solved, thanks again!
