### ISSUE TITLE
Error with CPU Part 1, execution of Full Multiome Tutorial

### ISSUE THREAD

**Issue by emix-c** [pinellolab/dictys#69]
**Checks before submitting the issue**
* [x] I installed the latest Dictys version successfully
* [x] I downloaded the whole folder for the tutorial
* [x] I ran the tutorial cells and notebooks (if more than one) in the correct order and only once
* [x] The preceeding cells and notebooks finished successfully (i.e. the reported error is the first encountered)

**Describe the error**
* How did you install Dictys (which option)?
I installed using conda. 
* Which tutorial?
The full multiome tutorial. 
* What (full message) and where (cell and notebook being executed) was the error?
I am encountering an error when trying to run the CPU Part1, execution block. 
I am specifically running into an error with Subset5, I am not seeing this error with any else. 
I adjusted the number of threads so that my system could handle it. Before, when I had it set to -j 36, some of the make commands to make expression0.tsv.gz were getting killed. 
Whenever I made adjustments, I deleted the entire tmp_static folder and reran the below block. 

%%bash
set -eo pipefail
cd ..
#Run CPU part of inference
make -f makefiles/static.mk -j 8 -k cpu || true

I ran into this error: 
Traceback (most recent call last):
  File "/home/exacloud/gscratch/CEDAR/chaoe/miniconda3/envs/dictys/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/exacloud/gscratch/CEDAR/chaoe/miniconda3/envs/dictys/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/exacloud/gscratch/CEDAR/chaoe/miniconda3/envs/dictys/lib/python3.9/site-packages/dictys/__main__.py", line 13, in <module>
    docstringrunner(__package__)
  File "/home/exacloud/gscratch/CEDAR/chaoe/miniconda3/envs/dictys/lib/python3.9/site-packages/docstring2argparse/__init__.py", line 340, in docstringrunner
    run_args(pkgname,funcs,args)
  File "/home/exacloud/gscratch/CEDAR/chaoe/miniconda3/envs/dictys/lib/python3.9/site-packages/docstring2argparse/__init__.py", line 330, in run_args
    return func(*a,**ka)
  File "/home/exacloud/gscratch/CEDAR/chaoe/miniconda3/envs/dictys/lib/python3.9/site-packages/dictys/chromatin.py", line 67, in macs2
    d2 = shell.cmdfile(cmd,[],infiles={'cellnames.txt': namestxt},quiet=False,cd=True)
  File "/home/exacloud/gscratch/CEDAR/chaoe/miniconda3/envs/dictys/lib/python3.9/site-packages/dictys/utils/shell.py", line 181, in cmdfile
    raise RuntimeError('Command failed, possibly due to program error: ' + cmda)
RuntimeError: Command failed, possibly due to program error: /home/exacloud/gscratch/CEDAR/chaoe/miniconda3/envs/dictys/lib/python3.9/site-packages/dictys/scripts/chromatin_macs2.sh cellnames.txt /home/groups/CEDAR/chaoe/projects/Dictys/data/bams /home/groups/CEDAR/chaoe/projects/Dictys/tmp_static/Subset5/reads.bam /home/groups/CEDAR/chaoe/projects/Dictys/tmp_static/Subset5/reads.bai /home/groups/CEDAR/chaoe/projects/Dictys/tmp_static/Subset5/peaks.bed hs 0.05 8
[bam_sort_core] merging from 2 files and 8 in-memory blocks...
/home/exacloud/gscratch/CEDAR/chaoe/miniconda3/envs/dictys/lib/python3.9/site-packages/dictys/scripts/chromatin_macs2.sh: line 38: 1597134 Killed                  samtools sort -o "$output_bam" $nodes2 -l 1 02-filtered.bam

make: *** [makefiles/common.mk:138: tmp_static/Subset5/reads.bam] Error 1
makefiles/common.mk:138: warning: pattern recipe did not update peer target 'tmp_static/Subset5/peaks.bed'.
makefiles/common.mk:138: warning: pattern recipe did not update peer target 'tmp_static/Subset5/reads.bai'.

* Did you deviate from any of the tutorial instructions?
No I didn't. 

**Optional steps (may accelerate troubleshooting)**
I did not do any optional steps. 

* Attach the error notebook and all preceeding notebooks with run output

**Comment by lingfeiwang** [comment]
Hi emix-c,

Probably your computer ran out of memory. Could you try again with `-j 4` instead?

Lingfei

**Comment by emix-c** [comment]
Hi Lingfei, 
Yes I got it working by reducing the number of jobs! 
I do have a quick question, since I'm running pytorch with CPU only, I only run 1.1 CPU part execution and then 4.1 Aggregating Network part execution, so I skip 2.1 GPU execution and 3.1 CPU part 2, execution, is that correct?

**Comment by lingfeiwang** [comment]
These errors are not provided in the tutorial notebook. Did you specify `DEVICE` to `cpu` in `2-makefile.ipynb` first? Are these the first error you encountered? I suggest to rerun the whole tutorial in a new folder to find and report the first error you encounter.
