### ISSUE TITLE
Question about network construction

### ISSUE THREAD

**Issue by OneHitKO** [pinellolab/dictys#71]
Hello! Thanks for developing Dictys, which we have ran successfully with interesting results! I only have a quick question on how the GRNs are inferred:

When scoring the TF links to potential target genes, is the covariation of target gene expression and motif-TF footprint score considered? Or is it only based on distance of TF footprint to target gene TSS? I am referring to the "TF binding network" part of the methods:

`To score the TF links to their potential target genes, we created a multipartite graph with the above outputs from each TF to its known motifs, from each motif to its containing footprints and from each footprint to its nearby genes (up to 500 kb from the TSS by default). Each motif–footprint link was scored additively based on the wellington footprint probability score W, Homer motif purity score H and the distance between footprint and target gene TSS D as log10 (W) + log10 (H) − 10−6(D)13. The maximum score over all directed paths was used for each TF–target link on the multipartite graph. This formed a continuous TF binding network with TF footprinting from chromatin accessibility profiles.`

Thanks for the clarification!

**Comment by lingfeiwang** [comment]
Great to hear that! By default Dictys does not use the covariation of target gene expression and motif-TF footprint score to infer the GRN. The "TF binding network" part of the method is the description for what Dictys does.

Lingfei
