### ISSUE TITLE
multiple samples

### ISSUE THREAD

**Issue by ASasasdasfasfasfasfasf** [pinellolab/dictys#73]
Hello, I am very interested in this tutorial, but one of the questions confuses me. The tutorial gives the process of analyzing a single sample, but how do I do it for multiple samples, I tried to merge the bam files but I encounter barcode duplication, please help me!

**Comment by lingfeiwang** [comment]
Thank you for the interest. Please see our FAQ at https://github.com/pinellolab/dictys#faq. Let us know if you have further questions.
